✨ Add home page
SilviaBarcellini/bakend pull request #46
Opened 2021-03-28 21:40 UTC by SilviaBarcellini

- build and reboot home page
- import components
- add links to other pages
- style home page
- make home page responsive

2021-03-28 21:49 UTC, mrana17 approved these changes
Lgtm 🚀

2021-03-29 07:44 UTC, DNaunin approved these changes
Great Job! 🚀

2021-03-29 10:11 UTC, phlgr requested changes
You should fix the Navbar to the bottom of the page, so it is easier to navigate, and you don't have to scroll all the way down first.
Gj 🚀

2021-03-29 10:11 UTC, phlgr commented on pages/Form.tsx
> +      <div className={styles.container}>
Try removing the `min-width: 100vw` here to get rid of the vertical scroll bar

2021-03-29 10:11 UTC, phlgr commented on package.json
> +    "mongodb": "^3.6.5",
👍

2021-03-29 10:11 UTC, phlgr commented on pages/index.tsx
> +            <OpenNewPage /> */}
Remove this comment

2021-03-29 10:11 UTC, phlgr commented on pages/index.tsx
> +          </div> */}
Is this comment needed here?

2021-03-29 10:11 UTC, phlgr commented on styles/Form.module.css
> +  min-width: 100vw;
This is causing vertical scroll bars

2021-03-29 10:11 UTC, phlgr commented on styles/Home.module.css
> +} */
Remove commented code

2021-03-29 10:11 UTC, phlgr commented on pages/index.tsx
> +            </a>
These should be `Link` elements. Take a look here:
https://nextjs.org/docs/api-reference/next/link

2021-03-29 10:11 UTC, phlgr commented on styles/Form.module.css
> +  min-height: 100vh;
Why is this height here?

2021-03-29 14:09 UTC, merged